create or replace table workspace.silver.pit_stops (
    season INT,
    round INT,
    driver_id STRING,
    driver_number STRING,
    constructor_id STRING,
    stop_number INT,
    pit_in_lap INT,
    pit_out_lap INT,
    pit_in_time_ms BIGINT,
    pit_out_time_ms BIGINT,
    pit_lane_duration_ms BIGINT,
    stint_before INT,
    stint_after INT,
    compound_before STRING,
    compound_after STRING,
    tyre_life_before_laps INT,
    tyre_life_after_laps INT,
    is_complete BOOLEAN,
    is_accurate BOOLEAN,
    source_file STRING,
    source_modified_at TIMESTAMP,
    bronze_ingested_at TIMESTAMP,
    source_silver_updated_at TIMESTAMP,
    record_hash STRING,
    silver_updated_at TIMESTAMP
)