create or replace table workspace.silver.races (
	round int not null,
	season int not null,
	country string,
	location string,
	official_event_name string,
	event_date timestamp_ntz,
	event_name string,
	event_format string,
	session_1_name string,
	session_1_start_utc timestamp_ntz,
	session_2_name string,
	session_2_start_utc timestamp_ntz,
	session_3_name string,
	session_3_start_utc timestamp_ntz,
	session_4_name string,
	session_4_start_utc timestamp_ntz,
	session_5_name string,
	session_5_start_utc timestamp_ntz,
	f1_api_support boolean,
	source_file string,
	source_modified_at timestamp,
	bronze_ingested_at timestamp,
	silver_updated_at timestamp,
	record_hash string
)